output "file_path" {
  description = "Location of the file created"
  value       = local_file.example.filename
}

output "random_name" {
  description = "The random name generated by random_pet"
  value       = random_pet.my_pet.id
}